# Change these first
owner: Magic-Services # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: MagicLike
    url: https://magiclike.net
    assignees:
      - MagicLike
  - name: MagicLike (old)
    url: https://magiclike.codeberg.page
    #icon: https://magiclike.codeberg.page/images/827679288a.ico
  - name: MagicLike (old-old)
    url: https://magiclike.github.io
    icon: 
  - name: Startpage
    url: https://startpage.com
    icon: 
  - name: DuckDuckGo
    url: https://duckduckgo.com
    icon: 
  - name: GitHub 
    url: https://github.com
    icon: 
  - name: GitLab
    url: https://gitlab.com
    icon:
  - name: Codeberg
    url: https://codeberg.org
    icon:
  - name: Codepen
    url: https://codepen.io
    icon:
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 403 
  - name: Mastodon (mstdn.social)
    url: https://mstdn.social
    icon: 
  - name: Nitter (nitter.net)
    url: https://nitter.net
    icon: 
  - name: Libreddit (libreddit.spike.codes)
    url: https://libreddit.spike.codes
    icon: 
  - name: Invidious (invidious.snopyta.org)
    url: https://invidious.snopyta.org
    icon: 
  - name: Piped (piped.kavin.rocks)
    url: https://piped.kavin.rocks
    icon: 
  - name: Peertube (peertube.tv)
    url: https://tube.tchncs.de
    icon:
  - name: Pixelfed
    url: https://pixelfed.org
    icon:
  - name: Pixelfed (pixey.org)
    url: https://pixey.org
    icon:
  - name: FediDB
    url: https://fedidb.org
    icon:
  - name: Ferdium
    url: https://ferdium.org
    icon:
  - name: Liberapay
    url: https://liberapay.com
    icon:
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 403
  - name: Open Collective
    url: https://opencollective.com
    icon:
  - name: Buy Me a Coffe
    url: https://buymeacoffee.com
    icon:
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 403
  - name: Kutt
    url: https://kutt.it
    icon:
  - name: umami (instance)
    url: $UMAMI_INSTANCE
    icon:
  - name: Shields.io
    url: https://shields.io
    icon:
  - name: Crowdin
    url: https://crowdin.com
    icon:
  - name: Webblate
    url: https://weblate.org
    icon:
  - name: Webblate (hosted.weblate.org)
    url: https://hosted.weblate.org
    icon:
  - name: Nextcloud (semi-public instance)
    url: $NC_SEMI_PUBLIC
    icon:
  - name: Cryptpad
    url: https://cryptpad.fr
    icon:
  - name: Steam
    url: https://store.steampowered.com
    icon: 
  - name: Steam Community
    url: https://steamcommunity.com
    icon: 
  - name: SteamDB
    url: https://steamdb.info
    icon:
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 403
      - 503
  - name: Epic Games Store
    url: https://epicgames.com
    icon: 
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302
      - 403
      - 503
  - name: itch.io
    url: https://itch.io
    icon: 
  - name: GOG.com
    url: https://gog.com
    icon: 
  - name: Tutanota
    url: https://tutanota.com
    icon: 
  - name: Protonmail
    url: https://protonmail.com
    icon: 
  - name: Mullvad VPN
    url: https://mullvad.net
    icon: 
  - name: Discord
    url: https://discord.com
    icon: 
  - name: Torproject
    url: https://torproject.org
    icon: 
  - name: Bitwarden
    url: https://bitwarden.com
    icon:
  - name: Folding @ Home
    url: https://foldingathome.org
    icon:
  - name: Internet Archive
    url: https://archive.org
    icon:
  - name: AlternativeTo
    url: https://alternativeto.net
    icon:

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.magiclike.net
  # baseUrl: /upptime
  logoUrl: https://magiclike.net/assets/MagicLike_275px.webp
  name: Upptime
  introTitle: "MagicLike's uptime monitor"
  introMessage: This status page monitors a collection of public websites.
  navbar:
    - title: Dashboard
      href: https://magic-services.github.io/upptime
    - title: GitHub
      href: https://github.com/MagicLike
    - title: Website
      href: https://magiclike.codeberg.page
  theme: dark
  favicon: https://magiclike.net/assets/favicon.ico
  customHeadHtml: <script async defer data-website-id="dac16ffb-425e-4f94-adb9-9a52ac6bfa2c" src="https://magiclytics.magiclike.net/magiclytics.js"></script>
  user-agent: Magic-Services

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
