# Change these first
owner: Magic-Services # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

sites:
  - name: MagicLike
    url: https://magiclike.github.io
  - name: DuckDuckGo
    url: https://duckduckgo.com
  - name: Mastodon
    url: https://mastodon.social
  - name: Libreddit
    url: https://libreddit.spike.codes
  - name: Nitter
    url: https://nitter.net
  - name: Invidious
    url: https://invidious.snopyta.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: 
  baseUrl: /Upptime
  logoUrl: https://magiclike.github.io/images/827679288a.jpg
  name: Upptime
  introTitle: "MagicLike's uptime monitor"
  introMessage: This status page monitors my personal collection of websites.
  navbar:
    - title: Dashboard
      href: https://magic-services.github.io/Upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://magiclike.github.io
  theme: dark
  customHeadHtml: <link rel="icon" href="https://magiclike.github.io/images/827679288a.ico">
  user-agent: Magic-Services

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
